/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Math;

/**
 *
 * @author amsta5248
 */
public class Mathmethods extends javax.swing.JFrame {

    /**
     * Creates new form Mathmethods
     */
    public Mathmethods() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        question1 = new javax.swing.JLabel();
        txtfieldnum1 = new javax.swing.JTextField();
        txtfieldnum2 = new javax.swing.JTextField();
        answernum1 = new javax.swing.JLabel();
        Buttonnum1 = new javax.swing.JButton();
        question2 = new javax.swing.JLabel();
        txtfieldnum3 = new javax.swing.JTextField();
        txtfieldnum4 = new javax.swing.JTextField();
        Buttonnum2 = new javax.swing.JButton();
        answernum2 = new javax.swing.JLabel();
        question3 = new javax.swing.JLabel();
        txtfield5 = new javax.swing.JTextField();
        txtfield6 = new javax.swing.JTextField();
        Buttonnum3 = new javax.swing.JButton();
        answernum3 = new javax.swing.JLabel();
        question4 = new javax.swing.JLabel();
        txtfield7 = new javax.swing.JTextField();
        txtfield8 = new javax.swing.JTextField();
        Buttonum4 = new javax.swing.JButton();
        answernum4 = new javax.swing.JLabel();
        question5 = new javax.swing.JLabel();
        txtfield9 = new javax.swing.JTextField();
        Buttonnum5 = new javax.swing.JButton();
        answernum5 = new javax.swing.JLabel();
        question6 = new javax.swing.JLabel();
        txtfield10 = new javax.swing.JTextField();
        Buttonnum6 = new javax.swing.JButton();
        answernum6 = new javax.swing.JLabel();
        question7 = new javax.swing.JLabel();
        txtfield11 = new javax.swing.JTextField();
        Buttonnum7 = new javax.swing.JButton();
        ansernum7 = new javax.swing.JLabel();
        question8 = new javax.swing.JLabel();
        txtfield12 = new javax.swing.JTextField();
        Buttonnum8 = new javax.swing.JButton();
        answernum8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title.setText("Math Methods");

        question1.setText("Enter two numbers and clickl to find out which number is larger. ");

        txtfieldnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldnum1ActionPerformed(evt);
            }
        });

        answernum1.setText("here");

        Buttonnum1.setText("Press");
        Buttonnum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnum1ActionPerformed(evt);
            }
        });

        question2.setText("Enter two number and click to find out which one is smaller.");

        txtfieldnum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldnum3ActionPerformed(evt);
            }
        });

        Buttonnum2.setText("Press");
        Buttonnum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnum2ActionPerformed(evt);
            }
        });

        answernum2.setText("here\n");

        question3.setText("Enter two number and press click to find out what is the power of the second number. ");

        txtfield6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield6ActionPerformed(evt);
            }
        });

        Buttonnum3.setText("Press");
        Buttonnum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnum3ActionPerformed(evt);
            }
        });

        answernum3.setText("here");

        question4.setText("Enter length of two sides of a right angel triangle to find out what is the hypotenuse.");

        Buttonum4.setText("Press");
        Buttonum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonum4ActionPerformed(evt);
            }
        });

        answernum4.setText("here");

        question5.setText("Enter a decimal number and click to round down to the nearst intengere.");

        Buttonnum5.setText("Press");
        Buttonnum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnum5ActionPerformed(evt);
            }
        });

        answernum5.setText("here");

        question6.setText("Enter a decimal number and click to roundup to the neast intengere.");

        Buttonnum6.setText("Press");
        Buttonnum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnum6ActionPerformed(evt);
            }
        });

        answernum6.setText("here");

        question7.setText("Enter integer and click to find square loot.");

        Buttonnum7.setText("Press");
        Buttonnum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnum7ActionPerformed(evt);
            }
        });

        ansernum7.setText("here");

        question8.setText("Enter an angels in degrees and click to find the angel in radinass ");

        Buttonnum8.setText("Press");
        Buttonnum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Buttonnum8ActionPerformed(evt);
            }
        });

        answernum8.setText("here");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(Title))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfield5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtfield6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Buttonnum3)
                                .addGap(58, 58, 58)
                                .addComponent(answernum3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(question1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfieldnum3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfieldnum4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Buttonnum2)
                                .addGap(67, 67, 67)
                                .addComponent(answernum2))
                            .addComponent(question3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfield7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtfield8, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Buttonum4)
                                .addGap(65, 65, 65)
                                .addComponent(answernum4))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtfieldnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtfieldnum2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Buttonnum1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(answernum1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(question2))
                            .addComponent(question8)
                            .addComponent(question6)
                            .addComponent(question5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfield9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(Buttonnum5)
                                .addGap(54, 54, 54)
                                .addComponent(answernum5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(question7)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtfield12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(41, 41, 41)
                                                    .addComponent(Buttonnum8))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(txtfield11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(Buttonnum7)))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(35, 35, 35)
                                                    .addComponent(ansernum7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGap(24, 24, 24)
                                                    .addComponent(answernum8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(txtfield10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(46, 46, 46)
                                            .addComponent(Buttonnum6)
                                            .addGap(71, 71, 71)
                                            .addComponent(answernum6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(80, 80, 80))
                                .addComponent(question4, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(question1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfieldnum1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfieldnum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(answernum1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonnum1))
                        .addGap(36, 36, 36)
                        .addComponent(question2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfieldnum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfieldnum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonnum2)
                            .addComponent(answernum2))
                        .addGap(33, 33, 33)
                        .addComponent(question3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Buttonnum3)
                            .addComponent(answernum3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfield6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfield5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addComponent(question4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfield7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfield8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonum4)
                            .addComponent(answernum4))
                        .addGap(36, 36, 36)
                        .addComponent(question5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfield9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonnum5)
                            .addComponent(answernum5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(question6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfield10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonnum6)
                            .addComponent(answernum6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(question7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtfield11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buttonnum7)))
                    .addComponent(ansernum7, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(question8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfield12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buttonnum8)
                    .addComponent(answernum8, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtfieldnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldnum1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldnum1ActionPerformed

    private void txtfieldnum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldnum3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldnum3ActionPerformed

    private void txtfield6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfield6ActionPerformed

    private void Buttonnum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnum1ActionPerformed
        
        int answer;
        int num1 = Integer.parseInt(txtfieldnum1.getText());
        int num2 = Integer.parseInt(txtfieldnum2.getText());
        
        answer = (Math.max(num1,num2));
        answernum1.setText(String. valueOf(answer));
        
       
    }//GEN-LAST:event_Buttonnum1ActionPerformed

    private void Buttonnum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnum2ActionPerformed
      int answer1;
      int num4 = Integer.parseInt(txtfieldnum3.getText());
      int num5 = Integer.parseInt(txtfieldnum4.getText());
      
      answer1= (Math.min(num4,num5));
      answernum2.setText(String.valueOf(answer1));  
      
             
      
    }//GEN-LAST:event_Buttonnum2ActionPerformed

    private void Buttonnum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnum5ActionPerformed
        double answer5;
        double num10 = Double.parseDouble(txtfield9.getText());
        answer5= (Math.floor(num10));
        answernum5.setText(String. valueOf(answer5));
        
    }//GEN-LAST:event_Buttonnum5ActionPerformed

    private void Buttonnum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnum3ActionPerformed
      int answer2;
      int num6 = Integer.parseInt(txtfield5.getText());
      int num7 = Integer.parseInt(txtfield6.getText());
      answer2= (int) (Math.pow(num6,num7));
      
      answernum3. setText(String. valueOf(answer2));
      
     
      
             
              
    }//GEN-LAST:event_Buttonnum3ActionPerformed

    private void Buttonum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonum4ActionPerformed
        
        int answer3;
        int num8= Integer.parseInt(txtfield7.getText());
        int num9= Integer.parseInt(txtfield8.getText());
        
        answer3= (int) (Math.hypot(num8,num9));
        answernum4.setText(String.valueOf(answer3));
        
        
        
                 
               
        
    }//GEN-LAST:event_Buttonum4ActionPerformed

    private void Buttonnum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnum6ActionPerformed
        double answer6;
        double num11= Double.parseDouble(txtfield10.getText());
        answer6 = (int) (Math.round(num11));
        answernum6.setText(String. valueOf(answer6));
        
    }//GEN-LAST:event_Buttonnum6ActionPerformed

    private void Buttonnum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnum7ActionPerformed
        double answer7;
        double num12= Integer.parseInt(txtfield11.getText());
        answer7= (Math.sqrt(num12));
        ansernum7.setText(String. valueOf(answer7));
        
        
               
    }//GEN-LAST:event_Buttonnum7ActionPerformed

    private void Buttonnum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Buttonnum8ActionPerformed
      double answer8;
      double num13= Integer.parseInt(txtfield12.getText());
      answer8= (Math.toRadians(num13));
      answernum8.setText(String. valueOf(answer8));
      
    }//GEN-LAST:event_Buttonnum8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mathmethods.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mathmethods().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonnum1;
    private javax.swing.JButton Buttonnum2;
    private javax.swing.JButton Buttonnum3;
    private javax.swing.JButton Buttonnum5;
    private javax.swing.JButton Buttonnum6;
    private javax.swing.JButton Buttonnum7;
    private javax.swing.JButton Buttonnum8;
    private javax.swing.JButton Buttonum4;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel ansernum7;
    private javax.swing.JLabel answernum1;
    private javax.swing.JLabel answernum2;
    private javax.swing.JLabel answernum3;
    private javax.swing.JLabel answernum4;
    private javax.swing.JLabel answernum5;
    private javax.swing.JLabel answernum6;
    private javax.swing.JLabel answernum8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel question1;
    private javax.swing.JLabel question2;
    private javax.swing.JLabel question3;
    private javax.swing.JLabel question4;
    private javax.swing.JLabel question5;
    private javax.swing.JLabel question6;
    private javax.swing.JLabel question7;
    private javax.swing.JLabel question8;
    private javax.swing.JTextField txtfield10;
    private javax.swing.JTextField txtfield11;
    private javax.swing.JTextField txtfield12;
    private javax.swing.JTextField txtfield5;
    private javax.swing.JTextField txtfield6;
    private javax.swing.JTextField txtfield7;
    private javax.swing.JTextField txtfield8;
    private javax.swing.JTextField txtfield9;
    private javax.swing.JTextField txtfieldnum1;
    private javax.swing.JTextField txtfieldnum2;
    private javax.swing.JTextField txtfieldnum3;
    private javax.swing.JTextField txtfieldnum4;
    // End of variables declaration//GEN-END:variables
}
